<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}
// generated by Poedit from corkywall-highlighter-fr_FR.po, do not edit directly
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n > 1);','language'=>'fr_FR','pot-creation-date'=>'2024-01-02 14:31+0100','po-revision-date'=>'2024-01-02 14:35+0100','translation-revision-date'=>'2024-01-02 14:35+0100','project-id-version'=>'CorkyWall & Highlighter','x-generator'=>'Poedit 3.9','messages'=>['Polaroid'=>'Polaroid','Polaroid: Tilt Left'=>'Polaroid: Penché à droite et bouge sur hover','Scotch Tape'=>'Scotché Milieu haut','Polaroid: Tilt Right'=>'Polaroid: Penché à gauche  et bouge sur hover','Scotch Top Bottom'=>'Scotchés m=Milieu haut et bas','Scotch Top Corners '=>'Scotchés Coins haut gauche et droit ','Scotch Corners top left - bottom right'=>'Scotchés Coins haut gauche, bas droite','Scotch Middle left right'=>'Scotchés Mileiu gauche et droite','Pins Green'=>'Epingle Verte','Pins Blue'=>'Epingle Bleue','Pins Orange'=>'Epingle Orange','Cap plugins'=>'Plugins Cap','Cap plugins for image block.'=>'Plugins Cap pour le block image.','Carole Petithomme'=>'Carole Petithomme','https://moncoachwp.fr/'=>'https://moncoachwp.fr/']];
